// Code generated by ogen, DO NOT EDIT.

package antifraud_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1AuthLoginPost implements POST /api/v1/auth/login operation.
	//
	// Сценарии:
	// - 200: корректные credentials => accessToken.
	// - 401: неверный email/пароль (не раскрываем, что именно
	// неверно).
	// - 423: пользователь деактивирован (isActive=false).
	// - 422: формат email/пароля невалиден.
	//
	// POST /api/v1/auth/login
	APIV1AuthLoginPost(ctx context.Context, req *LoginRequest) (APIV1AuthLoginPostRes, error)
	// APIV1AuthRegisterPost implements POST /api/v1/auth/register operation.
	//
	// Сценарии:
	// - 201: пользователь создан, роль USER по умолчанию,
	// возвращается accessToken и профиль.
	// - 409: email уже используется.
	// - 422: не проходит валидация (email, пароль, возраст и т.д.).
	//
	// POST /api/v1/auth/register
	APIV1AuthRegisterPost(ctx context.Context, req *RegisterRequest) (APIV1AuthRegisterPostRes, error)
	// APIV1FraudRulesGet implements GET /api/v1/fraud-rules operation.
	//
	// Только ADMIN.
	// Сортировка: `priority` ASC
	// Сценарии:
	// - 200: список правил.
	//
	// GET /api/v1/fraud-rules
	APIV1FraudRulesGet(ctx context.Context) (APIV1FraudRulesGetRes, error)
	// APIV1FraudRulesIDDelete implements DELETE /api/v1/fraud-rules/{id} operation.
	//
	// **Важно:** Это soft-delete. Правило НЕ удаляется физически из
	// базы данных,
	// а помечается как неактивное (enabled = false).
	// Только ADMIN может деактивировать правила.
	// **Идемпотентность:**
	// - Повторный вызов для уже деактивированного правила =>
	// 204 (не ошибка)
	// - Несуществующее правило => 404
	// **Последствия деактивации:**
	// - Правило больше не применяется при проверке
	// транзакций
	// - Правило остаётся в базе и доступно через GET /fraud-rules/{id}
	// - Статистика по правилу сохраняется
	// **Восстановление:**
	// - ADMIN может снова активировать через PUT /fraud-rules/{id} с
	// enabled=true.
	//
	// DELETE /api/v1/fraud-rules/{id}
	APIV1FraudRulesIDDelete(ctx context.Context, params APIV1FraudRulesIDDeleteParams) (APIV1FraudRulesIDDeleteRes, error)
	// APIV1FraudRulesIDGet implements GET /api/v1/fraud-rules/{id} operation.
	//
	// Возвращает полную информацию о правиле антифрода.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Поля ответа:**
	// - id: уникальный идентификатор правила
	// - name: название правила
	// - description: описание для документации
	// - dslExpression: выражение на DSL
	// - enabled: активно ли правило (применяется при проверке
	// транзакций)
	// - priority: приоритет (меньше = выше, проверяется раньше)
	// - createdAt, updatedAt: временные метки.
	//
	// GET /api/v1/fraud-rules/{id}
	APIV1FraudRulesIDGet(ctx context.Context, params APIV1FraudRulesIDGetParams) (APIV1FraudRulesIDGetRes, error)
	// APIV1FraudRulesIDPut implements PUT /api/v1/fraud-rules/{id} operation.
	//
	// Только ADMIN. Полное обновление.
	// Допускается любой DSL
	// 422 возвращается при невалидных полях.
	//
	// PUT /api/v1/fraud-rules/{id}
	APIV1FraudRulesIDPut(ctx context.Context, req *FraudRuleUpdateRequest, params APIV1FraudRulesIDPutParams) (APIV1FraudRulesIDPutRes, error)
	// APIV1FraudRulesPost implements POST /api/v1/fraud-rules operation.
	//
	// Только ADMIN.
	// Допускается любой DSL
	// Валидация:
	// - name: 3..120 символов
	// - dslExpression: обязателен
	// - priority: >=1 (меньше — выше приоритет)
	// Сценарии:
	// - 201: создано
	// - 422: невалидные поля
	// - 409: правило с таким именем уже есть.
	//
	// POST /api/v1/fraud-rules
	APIV1FraudRulesPost(ctx context.Context, req *FraudRuleCreateRequest) (APIV1FraudRulesPostRes, error)
	// APIV1FraudRulesValidatePost implements POST /api/v1/fraud-rules/validate operation.
	//
	// Только ADMIN. Полезно для UI "проверить правило".
	// Сценарии:
	// - 200: валидно (isValid=true)
	// - 200: невалидно (isValid=false, errors заполнен).
	//
	// POST /api/v1/fraud-rules/validate
	APIV1FraudRulesValidatePost(ctx context.Context, req *DslValidateRequest) (APIV1FraudRulesValidatePostRes, error)
	// APIV1PingGet implements GET /api/v1/ping operation.
	//
	// Проверка работоспособности сервиса.
	// Возвращает 200 OK если сервис готов обрабатывать
	// запросы.
	//
	// GET /api/v1/ping
	APIV1PingGet(ctx context.Context) (*APIV1PingGetOK, error)
	// APIV1StatsMerchantsRiskGet implements GET /api/v1/stats/merchants/risk operation.
	//
	// Только ADMIN.
	// Метрики по merchantId/merchantCategoryCode:
	// - txCount, gmv
	// - declineRate
	// - fraudRate.
	//
	// GET /api/v1/stats/merchants/risk
	APIV1StatsMerchantsRiskGet(ctx context.Context, params APIV1StatsMerchantsRiskGetParams) (APIV1StatsMerchantsRiskGetRes, error)
	// APIV1StatsOverviewGet implements GET /api/v1/stats/overview operation.
	//
	// Возвращает агрегированные метрики за указанный
	// период для дашборда.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Ограничения периода:**
	// - from < to (иначе 422)
	// - Максимальный период: 90 дней (иначе 422)
	// - Если from/to не указаны — последние 30 дней
	// **Метрики:**
	// - volume: общее количество транзакций
	// - gmv: Gross Merchandise Value (сумма всех транзакций)
	// - approvalRate: доля APPROVED транзакций (0..1)
	// - declineRate: доля DECLINED транзакций (0..1)
	// - topRiskMerchants: топ-10 мерчантов по declineRate.
	//
	// GET /api/v1/stats/overview
	APIV1StatsOverviewGet(ctx context.Context, params APIV1StatsOverviewGetParams) (APIV1StatsOverviewGetRes, error)
	// APIV1StatsRulesMatchesGet implements GET /api/v1/stats/rules/matches operation.
	//
	// Возвращает статистику по срабатываниям правил
	// антифрода за период.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Ограничения периода:**
	// - from < to (иначе 422)
	// - Максимальный период: 90 дней (иначе 422)
	// - Если from/to не указаны — последние 30 дней
	// **Метрики для каждого правила:**
	// - matches: сколько раз правило сработало (matched=true)
	// - uniqueUsers: сколько уникальных пользователей затронуто
	// - uniqueMerchants: сколько уникальных мерчантов затронуто
	// - shareOfDeclines: доля DECLINED транзакций, где это правило было
	// среди matched
	// Результаты отсортированы по matches DESC.
	//
	// GET /api/v1/stats/rules/matches
	APIV1StatsRulesMatchesGet(ctx context.Context, params APIV1StatsRulesMatchesGetParams) (APIV1StatsRulesMatchesGetRes, error)
	// APIV1StatsTransactionsTimeseriesGet implements GET /api/v1/stats/transactions/timeseries operation.
	//
	// Возвращает временной ряд метрик транзакций для
	// построения графиков.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Ограничения периода:**
	// - from < to (иначе 422)
	// - Максимальный период: 90 дней (иначе 422)
	// - Если from/to не указаны — последние 7 дней
	// **Группировка (groupBy):**
	// - hour: точки по часам (макс период 7 дней)
	// - day: точки по дням (макс период 90 дней)
	// - week: точки по неделям (макс период 1 год)
	// **Метрики в каждой точке:**
	// - txCount: количество транзакций
	// - gmv: сумма транзакций
	// - approvalRate, declineRate: доли по статусам.
	//
	// GET /api/v1/stats/transactions/timeseries
	APIV1StatsTransactionsTimeseriesGet(ctx context.Context, params APIV1StatsTransactionsTimeseriesGetParams) (APIV1StatsTransactionsTimeseriesGetRes, error)
	// APIV1StatsUsersIDRiskProfileGet implements GET /api/v1/stats/users/{id}/risk-profile operation.
	//
	// Доступ:
	// - ADMIN: любой пользователь
	// - USER: только свой (id == id в токене)
	// Метрики:
	// - txCount_24h / gmv_24h
	// - distinctDevices_24h / distinctIps_24h / distinctCities_24h
	// - declineRate_30d
	// - lastSeenAt.
	//
	// GET /api/v1/stats/users/{id}/risk-profile
	APIV1StatsUsersIDRiskProfileGet(ctx context.Context, params APIV1StatsUsersIDRiskProfileGetParams) (APIV1StatsUsersIDRiskProfileGetRes, error)
	// APIV1TransactionsBatchPost implements POST /api/v1/transactions/batch operation.
	//
	// Батч поддерживает частичный успех.
	// Сценарии:
	// - 201: все элементы обработаны успешно (каждый элемент
	// может быть APPROVED или DECLINED)
	// - 207: частичный успех (есть элементы, которые не
	// созданы из-за 422/403/409 и т.п.)
	// Для сопоставления используется index (0-based).
	//
	// POST /api/v1/transactions/batch
	APIV1TransactionsBatchPost(ctx context.Context, req *TransactionBatchCreateRequest) (APIV1TransactionsBatchPostRes, error)
	// APIV1TransactionsGet implements GET /api/v1/transactions operation.
	//
	// Доступ:
	// - ADMIN: все транзакции
	// - USER: только свои
	// Фильтры:
	// - userId (только ADMIN)
	// - status, isFraud
	// - from/to (RFC3339)
	// - page/size.
	//
	// GET /api/v1/transactions
	APIV1TransactionsGet(ctx context.Context, params APIV1TransactionsGetParams) (APIV1TransactionsGetRes, error)
	// APIV1TransactionsIDGet implements GET /api/v1/transactions/{id} operation.
	//
	// - ADMIN: любая транзакция
	// - USER: только свои.
	//
	// GET /api/v1/transactions/{id}
	APIV1TransactionsIDGet(ctx context.Context, params APIV1TransactionsIDGetParams) (APIV1TransactionsIDGetRes, error)
	// APIV1TransactionsPost implements POST /api/v1/transactions operation.
	//
	// Создаёт транзакцию (покупку) и проверяет её по всем
	// активным правилам антифрода.
	// **Важно:** Отклонение антифродом — это НЕ ошибка, а
	// бизнес-решение.
	// Поэтому 201 возвращается и для APPROVED, и для DECLINED
	// транзакций.
	// **Права доступа:**
	// - USER: может создавать транзакции только для себя (userId в
	// теле == id в токене)
	// - ADMIN: может создавать транзакции для любого
	// пользователя
	// **Алгоритм проверки антифрода:**
	// 1. Получить профиль пользователя (userId) из БД
	// 2. Загрузить все активные правила (enabled=true),
	// отсортированные по priority ASC
	// 3. Для каждого правила: распарсить dslExpression и вычислить
	// результат (matched=False для правил с невалидным DSL)
	// 4. Если хотя бы одно правило matched=true => status=DECLINED, isFraud=true
	// 5. Иначе => status=APPROVED, isFraud=false
	// 6. Сохранить транзакцию вместе с результатами всех
	// правил (ruleResults)
	// **Коды ответов:**
	// - 201: транзакция создана (APPROVED или DECLINED)
	// - 403: USER пытается создать транзакцию для другого
	// пользователя или пользователь деактивирован
	// - 404: пользователь с указанным userId не найден
	// - 422: невалидные поля (amount <= 0, некорректная валюта и т.д.).
	//
	// POST /api/v1/transactions
	APIV1TransactionsPost(ctx context.Context, req *TransactionCreateRequest) (APIV1TransactionsPostRes, error)
	// APIV1UsersGet implements GET /api/v1/users operation.
	//
	// Только ADMIN.
	// Сценарии:
	// - 200: страница пользователей
	// - 422: некорректные page/size.
	//
	// GET /api/v1/users
	APIV1UsersGet(ctx context.Context, params APIV1UsersGetParams) (APIV1UsersGetRes, error)
	// APIV1UsersIDDelete implements DELETE /api/v1/users/{id} operation.
	//
	// **Важно:** Это soft-delete. Пользователь НЕ удаляется
	// физически из базы данных,
	// а помечается как неактивный (isActive = false).
	// Только ADMIN может деактивировать пользователей.
	// **Идемпотентность:**
	// - Повторный вызов для уже деактивированного
	// пользователя => 204 (не ошибка)
	// - Несуществующий пользователь => 404
	// **Последствия деактивации:**
	// - POST /auth/login => 423 USER_INACTIVE
	// - POST /transactions с userId деактивированного => 403 FORBIDDEN
	// - Все существующие токены пользователя продолжают
	// работать до истечения (1 час)
	// **Восстановление:**
	// - ADMIN может снова активировать через PUT /users/{id} с isActive=true.
	//
	// DELETE /api/v1/users/{id}
	APIV1UsersIDDelete(ctx context.Context, params APIV1UsersIDDeleteParams) (APIV1UsersIDDeleteRes, error)
	// APIV1UsersIDGet implements GET /api/v1/users/{id} operation.
	//
	// Доступ:
	// - ADMIN: любой пользователь
	// - USER: только собственный профиль (id == sub/id в токене)
	// Сценарии:
	// - 200: найден
	// - 403: попытка USER прочитать чужой профиль
	// - 404: не найден.
	//
	// GET /api/v1/users/{id}
	APIV1UsersIDGet(ctx context.Context, params APIV1UsersIDGetParams) (APIV1UsersIDGetRes, error)
	// APIV1UsersIDPut implements PUT /api/v1/users/{id} operation.
	//
	// Полное обновление профиля. Необходимо передать все
	// поля.
	// Чтобы очистить поле, передайте null.
	// **Обязательные поля:** fullName, age, region, gender, maritalStatus
	// **Поля, которые могут быть null:** age, region, gender, maritalStatus
	// **Поля, которые НЕ могут быть null:** fullName
	// **Права доступа:**
	// - ADMIN: может обновлять любой профиль, включая role и isActive
	// - USER: только свой профиль (id в URL == id в токене)
	// **Ограничения для USER:**
	// - Попытка изменить role => 403 FORBIDDEN
	// - Попытка изменить isActive => 403 FORBIDDEN
	// - Попытка обновить чужой профиль => 403 FORBIDDEN
	// **Валидация:**
	// - fullName: 2-200 символов (обязательный, не может быть null)
	// - age: 18-120 или null
	// - region: до 32 символов или null
	// - email изменить нельзя (игнорируется, если передан).
	//
	// PUT /api/v1/users/{id}
	APIV1UsersIDPut(ctx context.Context, req *UserUpdateRequest, params APIV1UsersIDPutParams) (APIV1UsersIDPutRes, error)
	// APIV1UsersMeGet implements GET /api/v1/users/me operation.
	//
	// Возвращает профиль пользователя, определённого по JWT
	// токену.
	// Удобный способ получить свой профиль без знания
	// своего ID.
	// Доступно для любой роли (ADMIN, USER).
	//
	// GET /api/v1/users/me
	APIV1UsersMeGet(ctx context.Context) (APIV1UsersMeGetRes, error)
	// APIV1UsersMePut implements PUT /api/v1/users/me operation.
	//
	// Полное обновление профиля текущего пользователя.
	// Необходимо передать все поля. Чтобы очистить поле,
	// передайте null.
	// **Обязательные поля:** fullName, age, region, gender, maritalStatus
	// **Поля, которые могут быть null:** age, region, gender, maritalStatus
	// **Поля, которые НЕ могут быть null:** fullName
	// **Ограничения для USER:**
	// - Нельзя менять role — вернёт 403
	// - Нельзя менять isActive — вернёт 403
	// ADMIN может менять любые поля своего профиля, включая role
	// и isActive.
	//
	// PUT /api/v1/users/me
	APIV1UsersMePut(ctx context.Context, req *UserUpdateRequest) (APIV1UsersMePutRes, error)
	// APIV1UsersPost implements POST /api/v1/users operation.
	//
	// Только ADMIN. В ответе нет токенов (создание "из админки").
	// Сценарии:
	// - 201: создан
	// - 409: email занят
	// - 422: не проходит валидация полей (пароль/роль/возраст
	// и т.д.).
	//
	// POST /api/v1/users
	APIV1UsersPost(ctx context.Context, req *UserCreateRequest) (APIV1UsersPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
