// Code generated by ogen, DO NOT EDIT.

package antifraud_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginPostOperation                  OperationName = "AuthLoginPost"
	AuthRegisterPostOperation               OperationName = "AuthRegisterPost"
	FraudRulesGetOperation                  OperationName = "FraudRulesGet"
	FraudRulesIDDeleteOperation             OperationName = "FraudRulesIDDelete"
	FraudRulesIDGetOperation                OperationName = "FraudRulesIDGet"
	FraudRulesIDPutOperation                OperationName = "FraudRulesIDPut"
	FraudRulesPostOperation                 OperationName = "FraudRulesPost"
	FraudRulesValidatePostOperation         OperationName = "FraudRulesValidatePost"
	PingGetOperation                        OperationName = "PingGet"
	StatsMerchantsRiskGetOperation          OperationName = "StatsMerchantsRiskGet"
	StatsOverviewGetOperation               OperationName = "StatsOverviewGet"
	StatsRulesMatchesGetOperation           OperationName = "StatsRulesMatchesGet"
	StatsTransactionsTimeseriesGetOperation OperationName = "StatsTransactionsTimeseriesGet"
	StatsUsersIDRiskProfileGetOperation     OperationName = "StatsUsersIDRiskProfileGet"
	TransactionsBatchPostOperation          OperationName = "TransactionsBatchPost"
	TransactionsGetOperation                OperationName = "TransactionsGet"
	TransactionsIDGetOperation              OperationName = "TransactionsIDGet"
	TransactionsPostOperation               OperationName = "TransactionsPost"
	UsersGetOperation                       OperationName = "UsersGet"
	UsersIDDeleteOperation                  OperationName = "UsersIDDelete"
	UsersIDGetOperation                     OperationName = "UsersIDGet"
	UsersIDPutOperation                     OperationName = "UsersIDPut"
	UsersMeGetOperation                     OperationName = "UsersMeGet"
	UsersMePutOperation                     OperationName = "UsersMePut"
	UsersPostOperation                      OperationName = "UsersPost"
)
