// Code generated by ogen, DO NOT EDIT.
package antifraud_v1

type APIV1AuthLoginPostRes interface {
	aPIV1AuthLoginPostRes()
}

type APIV1AuthRegisterPostRes interface {
	aPIV1AuthRegisterPostRes()
}

type APIV1FraudRulesGetRes interface {
	aPIV1FraudRulesGetRes()
}

type APIV1FraudRulesIDDeleteRes interface {
	aPIV1FraudRulesIDDeleteRes()
}

type APIV1FraudRulesIDGetRes interface {
	aPIV1FraudRulesIDGetRes()
}

type APIV1FraudRulesIDPutRes interface {
	aPIV1FraudRulesIDPutRes()
}

type APIV1FraudRulesPostRes interface {
	aPIV1FraudRulesPostRes()
}

type APIV1FraudRulesValidatePostRes interface {
	aPIV1FraudRulesValidatePostRes()
}

type APIV1StatsMerchantsRiskGetRes interface {
	aPIV1StatsMerchantsRiskGetRes()
}

type APIV1StatsOverviewGetRes interface {
	aPIV1StatsOverviewGetRes()
}

type APIV1StatsRuleMatchesGetRes interface {
	aPIV1StatsRuleMatchesGetRes()
}

type APIV1StatsTransactionsTimeseriesGetRes interface {
	aPIV1StatsTransactionsTimeseriesGetRes()
}

type APIV1StatsUsersIDRiskProfileGetRes interface {
	aPIV1StatsUsersIDRiskProfileGetRes()
}

type APIV1TransactionsBatchPostRes interface {
	aPIV1TransactionsBatchPostRes()
}

type APIV1TransactionsGetRes interface {
	aPIV1TransactionsGetRes()
}

type APIV1TransactionsIDGetRes interface {
	aPIV1TransactionsIDGetRes()
}

type APIV1TransactionsPostRes interface {
	aPIV1TransactionsPostRes()
}

type APIV1UsersGetRes interface {
	aPIV1UsersGetRes()
}

type APIV1UsersIDDeleteRes interface {
	aPIV1UsersIDDeleteRes()
}

type APIV1UsersIDGetRes interface {
	aPIV1UsersIDGetRes()
}

type APIV1UsersIDPutRes interface {
	aPIV1UsersIDPutRes()
}

type APIV1UsersMeGetRes interface {
	aPIV1UsersMeGetRes()
}

type APIV1UsersMePutRes interface {
	aPIV1UsersMePutRes()
}

type APIV1UsersPostRes interface {
	aPIV1UsersPostRes()
}
