// Code generated by ogen, DO NOT EDIT.
package antifraud_v1

type AuthLoginPostRes interface {
	authLoginPostRes()
}

type AuthRegisterPostRes interface {
	authRegisterPostRes()
}

type FraudRulesGetRes interface {
	fraudRulesGetRes()
}

type FraudRulesIDDeleteRes interface {
	fraudRulesIDDeleteRes()
}

type FraudRulesIDGetRes interface {
	fraudRulesIDGetRes()
}

type FraudRulesIDPutRes interface {
	fraudRulesIDPutRes()
}

type FraudRulesPostRes interface {
	fraudRulesPostRes()
}

type FraudRulesValidatePostRes interface {
	fraudRulesValidatePostRes()
}

type StatsMerchantsRiskGetRes interface {
	statsMerchantsRiskGetRes()
}

type StatsOverviewGetRes interface {
	statsOverviewGetRes()
}

type StatsRulesMatchesGetRes interface {
	statsRulesMatchesGetRes()
}

type StatsTransactionsTimeseriesGetRes interface {
	statsTransactionsTimeseriesGetRes()
}

type StatsUsersIDRiskProfileGetRes interface {
	statsUsersIDRiskProfileGetRes()
}

type TransactionsBatchPostRes interface {
	transactionsBatchPostRes()
}

type TransactionsGetRes interface {
	transactionsGetRes()
}

type TransactionsIDGetRes interface {
	transactionsIDGetRes()
}

type TransactionsPostRes interface {
	transactionsPostRes()
}

type UsersGetRes interface {
	usersGetRes()
}

type UsersIDDeleteRes interface {
	usersIDDeleteRes()
}

type UsersIDGetRes interface {
	usersIDGetRes()
}

type UsersIDPutRes interface {
	usersIDPutRes()
}

type UsersMeGetRes interface {
	usersMeGetRes()
}

type UsersMePutRes interface {
	usersMePutRes()
}

type UsersPostRes interface {
	usersPostRes()
}
