// Code generated by ogen, DO NOT EDIT.

package antifraud_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1AuthLoginPostOperation                  OperationName = "APIV1AuthLoginPost"
	APIV1AuthRegisterPostOperation               OperationName = "APIV1AuthRegisterPost"
	APIV1FraudRulesGetOperation                  OperationName = "APIV1FraudRulesGet"
	APIV1FraudRulesIDDeleteOperation             OperationName = "APIV1FraudRulesIDDelete"
	APIV1FraudRulesIDGetOperation                OperationName = "APIV1FraudRulesIDGet"
	APIV1FraudRulesIDPutOperation                OperationName = "APIV1FraudRulesIDPut"
	APIV1FraudRulesPostOperation                 OperationName = "APIV1FraudRulesPost"
	APIV1FraudRulesValidatePostOperation         OperationName = "APIV1FraudRulesValidatePost"
	APIV1PingGetOperation                        OperationName = "APIV1PingGet"
	APIV1StatsMerchantsRiskGetOperation          OperationName = "APIV1StatsMerchantsRiskGet"
	APIV1StatsOverviewGetOperation               OperationName = "APIV1StatsOverviewGet"
	APIV1StatsRuleMatchesGetOperation            OperationName = "APIV1StatsRuleMatchesGet"
	APIV1StatsTransactionsTimeseriesGetOperation OperationName = "APIV1StatsTransactionsTimeseriesGet"
	APIV1StatsUsersIDRiskProfileGetOperation     OperationName = "APIV1StatsUsersIDRiskProfileGet"
	APIV1TransactionsBatchPostOperation          OperationName = "APIV1TransactionsBatchPost"
	APIV1TransactionsGetOperation                OperationName = "APIV1TransactionsGet"
	APIV1TransactionsIDGetOperation              OperationName = "APIV1TransactionsIDGet"
	APIV1TransactionsPostOperation               OperationName = "APIV1TransactionsPost"
	APIV1UsersGetOperation                       OperationName = "APIV1UsersGet"
	APIV1UsersIDDeleteOperation                  OperationName = "APIV1UsersIDDelete"
	APIV1UsersIDGetOperation                     OperationName = "APIV1UsersIDGet"
	APIV1UsersIDPutOperation                     OperationName = "APIV1UsersIDPut"
	APIV1UsersMeGetOperation                     OperationName = "APIV1UsersMeGet"
	APIV1UsersMePutOperation                     OperationName = "APIV1UsersMePut"
	APIV1UsersPostOperation                      OperationName = "APIV1UsersPost"
)
