// Code generated by ogen, DO NOT EDIT.

package antifraud_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AuthLoginPost implements POST /auth/login operation.
	//
	// Сценарии:
	// - 200: корректные credentials => accessToken.
	// - 401: неверный email/пароль (не раскрываем, что именно
	// неверно).
	// - 423: пользователь деактивирован (isActive=false).
	// - 422: формат email/пароля невалиден.
	//
	// POST /auth/login
	AuthLoginPost(ctx context.Context, req *LoginRequest) (AuthLoginPostRes, error)
	// AuthRegisterPost implements POST /auth/register operation.
	//
	// Сценарии:
	// - 201: пользователь создан, роль USER по умолчанию,
	// возвращается accessToken и профиль.
	// - 409: email уже используется.
	// - 422: не проходит валидация (email, пароль, возраст и т.д.).
	//
	// POST /auth/register
	AuthRegisterPost(ctx context.Context, req *RegisterRequest) (AuthRegisterPostRes, error)
	// FraudRulesGet implements GET /fraud-rules operation.
	//
	// Только ADMIN.
	// Сценарии:
	// - 200: список правил.
	//
	// GET /fraud-rules
	FraudRulesGet(ctx context.Context) (FraudRulesGetRes, error)
	// FraudRulesIDDelete implements DELETE /fraud-rules/{id} operation.
	//
	// **Важно:** Это soft-delete. Правило НЕ удаляется физически из
	// базы данных,
	// а помечается как неактивное (enabled = false).
	// Только ADMIN может деактивировать правила.
	// **Идемпотентность:**
	// - Повторный вызов для уже деактивированного правила =>
	// 204 (не ошибка)
	// - Несуществующее правило => 404
	// **Последствия деактивации:**
	// - Правило больше не применяется при проверке
	// транзакций
	// - Правило остаётся в базе и доступно через GET /fraud-rules/{id}
	// - Статистика по правилу сохраняется
	// **Восстановление:**
	// - ADMIN может снова активировать через PUT /fraud-rules/{id} с
	// enabled=true.
	//
	// DELETE /fraud-rules/{id}
	FraudRulesIDDelete(ctx context.Context, params FraudRulesIDDeleteParams) (FraudRulesIDDeleteRes, error)
	// FraudRulesIDGet implements GET /fraud-rules/{id} operation.
	//
	// Возвращает полную информацию о правиле антифрода.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Поля ответа:**
	// - id: уникальный идентификатор правила
	// - name: название правила
	// - description: описание для документации
	// - dslExpression: выражение на DSL
	// - enabled: активно ли правило (применяется при проверке
	// транзакций)
	// - priority: приоритет (меньше = выше, проверяется раньше)
	// - createdAt, updatedAt: временные метки.
	//
	// GET /fraud-rules/{id}
	FraudRulesIDGet(ctx context.Context, params FraudRulesIDGetParams) (FraudRulesIDGetRes, error)
	// FraudRulesIDPut implements PUT /fraud-rules/{id} operation.
	//
	// Только ADMIN. Полное обновление.
	// 422 возвращается при невалидном DSL/полях.
	//
	// PUT /fraud-rules/{id}
	FraudRulesIDPut(ctx context.Context, req *FraudRuleUpdateRequest, params FraudRulesIDPutParams) (FraudRulesIDPutRes, error)
	// FraudRulesPost implements POST /fraud-rules operation.
	//
	// Только ADMIN.
	// Валидация:
	// - name: 3..120 символов
	// - dslExpression: обязателен, должен парситься по
	// спецификации DSL
	// - priority: >=1 (меньше — выше приоритет)
	// Сценарии:
	// - 201: создано
	// - 422: невалидные поля или DSL синтаксически неверен
	// - 409: правило с таким именем уже есть (если включена
	// уникальность имени).
	//
	// POST /fraud-rules
	FraudRulesPost(ctx context.Context, req *FraudRuleCreateRequest) (FraudRulesPostRes, error)
	// FraudRulesValidatePost implements POST /fraud-rules/validate operation.
	//
	// Только ADMIN. Полезно для UI "проверить правило".
	// Сценарии:
	// - 200: валидно (isValid=true)
	// - 200: невалидно (isValid=false, errors заполнен).
	//
	// POST /fraud-rules/validate
	FraudRulesValidatePost(ctx context.Context, req *DslValidateRequest) (FraudRulesValidatePostRes, error)
	// PingGet implements GET /ping operation.
	//
	// Проверка работоспособности сервиса.
	// Возвращает 200 OK если сервис готов обрабатывать
	// запросы.
	//
	// GET /ping
	PingGet(ctx context.Context) (*PingGetOK, error)
	// StatsMerchantsRiskGet implements GET /stats/merchants/risk operation.
	//
	// Только ADMIN.
	// Метрики по merchantId/merchantCategoryCode:
	// - txCount, gmv
	// - declineRate
	// - fraudRate.
	//
	// GET /stats/merchants/risk
	StatsMerchantsRiskGet(ctx context.Context, params StatsMerchantsRiskGetParams) (StatsMerchantsRiskGetRes, error)
	// StatsOverviewGet implements GET /stats/overview operation.
	//
	// Возвращает агрегированные метрики за указанный
	// период для дашборда.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Ограничения периода:**
	// - from < to (иначе 422)
	// - Максимальный период: 90 дней (иначе 422)
	// - Если from/to не указаны — последние 30 дней
	// **Метрики:**
	// - volume: общее количество транзакций
	// - gmv: Gross Merchandise Value (сумма всех транзакций)
	// - approvalRate: доля APPROVED транзакций (0..1)
	// - declineRate: доля DECLINED транзакций (0..1)
	// - topRiskMerchants: топ-10 мерчантов по declineRate.
	//
	// GET /stats/overview
	StatsOverviewGet(ctx context.Context, params StatsOverviewGetParams) (StatsOverviewGetRes, error)
	// StatsRulesMatchesGet implements GET /stats/rules/matches operation.
	//
	// Возвращает статистику по срабатываниям правил
	// антифрода за период.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Ограничения периода:**
	// - from < to (иначе 422)
	// - Максимальный период: 90 дней (иначе 422)
	// - Если from/to не указаны — последние 30 дней
	// **Метрики для каждого правила:**
	// - matches: сколько раз правило сработало (matched=true)
	// - uniqueUsers: сколько уникальных пользователей затронуто
	// - uniqueMerchants: сколько уникальных мерчантов затронуто
	// - shareOfDeclines: доля DECLINED транзакций, где это правило было
	// среди matched
	// Результаты отсортированы по matches DESC.
	//
	// GET /stats/rules/matches
	StatsRulesMatchesGet(ctx context.Context, params StatsRulesMatchesGetParams) (StatsRulesMatchesGetRes, error)
	// StatsTransactionsTimeseriesGet implements GET /stats/transactions/timeseries operation.
	//
	// Возвращает временной ряд метрик транзакций для
	// построения графиков.
	// Только ADMIN имеет доступ к этому эндпоинту.
	// **Ограничения периода:**
	// - from < to (иначе 422)
	// - Максимальный период: 90 дней (иначе 422)
	// - Если from/to не указаны — последние 7 дней
	// **Группировка (groupBy):**
	// - hour: точки по часам (макс период 7 дней)
	// - day: точки по дням (макс период 90 дней)
	// - week: точки по неделям (макс период 1 год)
	// **Метрики в каждой точке:**
	// - txCount: количество транзакций
	// - gmv: сумма транзакций
	// - approvalRate, declineRate: доли по статусам.
	//
	// GET /stats/transactions/timeseries
	StatsTransactionsTimeseriesGet(ctx context.Context, params StatsTransactionsTimeseriesGetParams) (StatsTransactionsTimeseriesGetRes, error)
	// StatsUsersIDRiskProfileGet implements GET /stats/users/{id}/risk-profile operation.
	//
	// Доступ:
	// - ADMIN: любой пользователь
	// - USER: только свой (id == id в токене)
	// Метрики:
	// - txCount_24h / gmv_24h
	// - distinctDevices_24h / distinctIps_24h / distinctCities_24h
	// - declineRate_30d
	// - lastSeenAt.
	//
	// GET /stats/users/{id}/risk-profile
	StatsUsersIDRiskProfileGet(ctx context.Context, params StatsUsersIDRiskProfileGetParams) (StatsUsersIDRiskProfileGetRes, error)
	// TransactionsBatchPost implements POST /transactions/batch operation.
	//
	// Батч поддерживает частичный успех.
	// Сценарии:
	// - 201: все элементы обработаны успешно (каждый элемент
	// может быть APPROVED или DECLINED)
	// - 207: частичный успех (есть элементы, которые не
	// созданы из-за 422/403/409 и т.п.)
	// Для сопоставления используется index (0-based).
	//
	// POST /transactions/batch
	TransactionsBatchPost(ctx context.Context, req *TransactionBatchCreateRequest) (TransactionsBatchPostRes, error)
	// TransactionsGet implements GET /transactions operation.
	//
	// Доступ:
	// - ADMIN: все транзакции
	// - USER: только свои
	// Фильтры:
	// - userId (только ADMIN)
	// - status, isFraud
	// - from/to (RFC3339)
	// - page/size.
	//
	// GET /transactions
	TransactionsGet(ctx context.Context, params TransactionsGetParams) (TransactionsGetRes, error)
	// TransactionsIDGet implements GET /transactions/{id} operation.
	//
	// - ADMIN: любая транзакция
	// - USER: только свои.
	//
	// GET /transactions/{id}
	TransactionsIDGet(ctx context.Context, params TransactionsIDGetParams) (TransactionsIDGetRes, error)
	// TransactionsPost implements POST /transactions operation.
	//
	// Создаёт транзакцию (покупку) и проверяет её по всем
	// активным правилам антифрода.
	// **Важно:** Отклонение антифродом — это НЕ ошибка, а
	// бизнес-решение.
	// Поэтому 201 возвращается и для APPROVED, и для DECLINED
	// транзакций.
	// **Права доступа:**
	// - USER: может создавать транзакции только для себя (userId в
	// теле == id в токене)
	// - ADMIN: может создавать транзакции для любого
	// пользователя
	// **Алгоритм проверки антифрода:**
	// 1. Получить профиль пользователя (userId) из БД
	// 2. Загрузить все активные правила (enabled=true),
	// отсортированные по priority ASC, затем по id ASC
	// 3. Для каждого правила: распарсить dslExpression и вычислить
	// результат
	// 4. Если хотя бы одно правило matched=true => status=DECLINED, isFraud=true
	// 5. Иначе => status=APPROVED, isFraud=false
	// 6. Сохранить транзакцию вместе с результатами всех
	// правил (ruleResults)
	// **Коды ответов:**
	// - 201: транзакция создана (APPROVED или DECLINED)
	// - 403: USER пытается создать транзакцию для другого
	// пользователя
	// - 404: пользователь с указанным userId не найден
	// - 422: невалидные поля (amount <= 0, некорректная валюта и т.д.).
	//
	// POST /transactions
	TransactionsPost(ctx context.Context, req *TransactionCreateRequest) (TransactionsPostRes, error)
	// UsersGet implements GET /users operation.
	//
	// Только ADMIN.
	// Сценарии:
	// - 200: страница пользователей
	// - 422: некорректные page/size.
	//
	// GET /users
	UsersGet(ctx context.Context, params UsersGetParams) (UsersGetRes, error)
	// UsersIDDelete implements DELETE /users/{id} operation.
	//
	// **Важно:** Это soft-delete. Пользователь НЕ удаляется
	// физически из базы данных,
	// а помечается как неактивный (isActive = false).
	// Только ADMIN может деактивировать пользователей.
	// **Идемпотентность:**
	// - Повторный вызов для уже деактивированного
	// пользователя => 204 (не ошибка)
	// - Несуществующий пользователь => 404
	// **Последствия деактивации:**
	// - POST /auth/login => 423 USER_INACTIVE
	// - POST /transactions с userId деактивированного => 403 FORBIDDEN
	// - Все существующие токены пользователя продолжают
	// работать до истечения (1 час)
	// **Восстановление:**
	// - ADMIN может снова активировать через PUT /users/{id} с isActive=true.
	//
	// DELETE /users/{id}
	UsersIDDelete(ctx context.Context, params UsersIDDeleteParams) (UsersIDDeleteRes, error)
	// UsersIDGet implements GET /users/{id} operation.
	//
	// Доступ:
	// - ADMIN: любой пользователь
	// - USER: только собственный профиль (id == sub/id в токене)
	// Сценарии:
	// - 200: найден
	// - 403: попытка USER прочитать чужой профиль
	// - 404: не найден.
	//
	// GET /users/{id}
	UsersIDGet(ctx context.Context, params UsersIDGetParams) (UsersIDGetRes, error)
	// UsersIDPut implements PUT /users/{id} operation.
	//
	// Полное обновление профиля. Необходимо передать все
	// поля.
	// Чтобы очистить поле, передайте null.
	// **Обязательные поля:** fullName, age, region, gender, maritalStatus
	// **Поля, которые могут быть null:** age, region, gender, maritalStatus
	// **Поля, которые НЕ могут быть null:** fullName
	// **Права доступа:**
	// - ADMIN: может обновлять любой профиль, включая role и isActive
	// - USER: только свой профиль (id в URL == id в токене)
	// **Ограничения для USER:**
	// - Попытка изменить role => 403 FORBIDDEN
	// - Попытка изменить isActive => 403 FORBIDDEN
	// - Попытка обновить чужой профиль => 403 FORBIDDEN
	// **Валидация:**
	// - fullName: 2-200 символов (обязательный, не может быть null)
	// - age: 18-120 или null
	// - region: до 32 символов или null
	// - email изменить нельзя (игнорируется, если передан).
	//
	// PUT /users/{id}
	UsersIDPut(ctx context.Context, req *UserUpdateRequest, params UsersIDPutParams) (UsersIDPutRes, error)
	// UsersMeGet implements GET /users/me operation.
	//
	// Возвращает профиль пользователя, определённого по JWT
	// токену.
	// Удобный способ получить свой профиль без знания
	// своего ID.
	// Доступно для любой роли (ADMIN, USER).
	//
	// GET /users/me
	UsersMeGet(ctx context.Context) (UsersMeGetRes, error)
	// UsersMePut implements PUT /users/me operation.
	//
	// Полное обновление профиля текущего пользователя.
	// Необходимо передать все поля. Чтобы очистить поле,
	// передайте null.
	// **Обязательные поля:** fullName, age, region, gender, maritalStatus
	// **Поля, которые могут быть null:** age, region, gender, maritalStatus
	// **Поля, которые НЕ могут быть null:** fullName
	// **Ограничения для USER:**
	// - Нельзя менять role — вернёт 403
	// - Нельзя менять isActive — вернёт 403
	// ADMIN может менять любые поля своего профиля, включая role
	// и isActive.
	//
	// PUT /users/me
	UsersMePut(ctx context.Context, req *UserUpdateRequest) (UsersMePutRes, error)
	// UsersPost implements POST /users operation.
	//
	// Только ADMIN. В ответе нет токенов (создание "из админки").
	// Сценарии:
	// - 201: создан
	// - 409: email занят
	// - 422: не проходит валидация полей (пароль/роль/возраст
	// и т.д.).
	//
	// POST /users
	UsersPost(ctx context.Context, req *UserCreateRequest) (UsersPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
