// Code generated by ogen, DO NOT EDIT.

package antifraud_v1

// setDefaults set default value of fields.
func (s *FraudRule) setDefaults() {
	{
		val := bool(true)
		s.Enabled = val
	}
}

// setDefaults set default value of fields.
func (s *FraudRuleCreateRequest) setDefaults() {
	{
		val := bool(true)
		s.Enabled.SetTo(val)
	}
	{
		val := int(100)
		s.Priority.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *User) setDefaults() {
	{
		val := bool(true)
		s.IsActive = val
	}
}
